baseURL = "https://qldbguide.com/"
languageCode = "en-gb"
title = "QLDB Guide"
theme = "compose"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

[Params]
    google_analytics_id = "UA-155541706-1"

    images = ["/images/QLDB_light-bg.png"]

    # Souce Code repository section
    description = "An open guide that walks through the basic concepts of Amazon QLDB"
    github_repository = "https://github.com/mlewis7127/qldbguide"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/mlewis7127/qldbguide"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

