baseURL = "https://qldbguide.com/"
languageCode = "en-gb"
title = "QLDB Guide"
theme = "hugo-theme-techdoc"

[Params]

    images = ["QLDB_light-bg.png"]

    # Souce Code repository section
    description = "An open guide that walks through the basic concepts of Amazon QLDB"
    github_repository = "https://github.com/mlewis7127/qldbguide"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/mlewis7127/qldbguide"

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu"

