baseURL = "https://qldbguide.com/"
languageCode = "en-gb"
title = "QLDB Guide"
theme = "hugo-theme-techdoc"

[Params]

    # Souce Code repository section
    description = "An open guide that walks through the basic concepts of Amazon QLDB"
